kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: node:14
    commands:
      - npm i
      - npm run eslint
      - npm run build:prod
  - name: dry-run-build
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: garykim/brooklynbooboos
      dry_run: true

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
